#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/syscall.h>

/*******************************************************************************
**         For Debug
*/

#define GETTID()	((long)syscall(SYS_gettid))

static char *font_color[6] = {
	"\033[0m", /* reset */
	"\033[31m", /* red */
	"\033[32m", /* green */
	"\033[34m", /* blue */
	"\033[35m", /* magenta */
	"\033[36m" /* cyan */
};
static long tids[6] = {0L, };
static int last_thread_idx = 0;

static long main_tid = 0;
static long sub_tid = 0;

void register_thread_font()
{
	tids[++last_thread_idx] = GETTID();
}

void print_with_color(const char *format, ...)
{
	long _tid = GETTID();
	int i, j;
	for (i = 1; i <= last_thread_idx; i++) {
		if (_tid == tids[i]) {
			for (j = 1; j < i; j++)
				printf("\t");
			printf("[%s%ld%s]", font_color[i], _tid, font_color[0]);
			va_list args;
			va_start(args, format);
			vprintf(format, args);
			va_end(args);
			printf("\n");
		}
	}
}

void font_guide()
{
	printf("=== font color guide ===\n");
	int i = 1;
	printf("%s%s%s\n", font_color[i++], "1st thread", font_color[0]);
	printf("%s%s%s\n", font_color[i++], "2nd thread", font_color[0]);
	printf("%s%s%s\n", font_color[i++], "3rd thread", font_color[0]);
	printf("%s%s%s\n", font_color[i++], "4th thread", font_color[0]);
	printf("%s%s%s\n", font_color[i++], "5th thread", font_color[0]);
	printf("========================\n\n");
}

/*
**         For Debug
*******************************************************************************/

gboolean _g_source_func(gpointer user_data)
{
	print_with_color("g_context_function (generated by %ld) <This tid is important!!>", (long)user_data);

	return FALSE;
}

void *test_runnable(void *data)
{
	register_thread_font();
	print_with_color("thread start >>>");
	sleep(1);

	print_with_color("gcontext invoke");
	GMainContext *_ctx = g_main_loop_get_context((GMainLoop *)data);
	g_main_context_invoke(_ctx, _g_source_func, (void *)GETTID());
	sleep(1);

	print_with_color("quit main loop");
	g_main_loop_quit((GMainLoop *)data);
	sleep(1);

	print_with_color("<<< thread end");
	return NULL;
}

int main()
{
	font_guide();
	GMainContext *ctx = g_main_context_new();
	GMainLoop *loop = g_main_loop_new(ctx, FALSE);

	register_thread_font();

	pthread_t th;
	pthread_create(&th, NULL, test_runnable, (void *)loop);

	print_with_color("main loop run");
	g_main_loop_run(loop);	
	print_with_color("main loop exit");
	sleep(1);

	return 0;
}
